name: MultDiary Build

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-windows:
    runs-on: windows-2022
    name: Windows Build
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install .NET 7.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      # MAUI framework is not installed by default.
      - name: Install MAUI
        run: dotnet workload install maui --ignore-failed-sources

      - name: Restore Dependencies
        run: dotnet restore src/Multidiary.csproj

      - name: Unit Tests
        run: dotnet test

      - name: Build Windows
        run: dotnet publish src/MultiDiary.csproj -c Release -f net7.0-windows10.0.19041.0 --no-restore

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Multi Diary
          path: src/bin/Release/net7.0-windows10.0.19041.0/win10-x64/AppPackages/MultiDiary*/MultiDiary*.msix